# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '=1.21'

    - name: Format
      run: test -z $(gofmt -l .)

    - name: Vet
      run: go vet -v ./...

    - name: Staticcheck
      run: go run honnef.co/go/tools/cmd/staticcheck@2023.1.7 ./...

    - name: Errcheck
      run: go run github.com/kisielk/errcheck@v1.7.0 -ignoretests ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -bench=. -short -v ./...
